board: PiBotV49PB
name: Genmitsu-4040-ProMax_PiBot_Upgrade_v19
meta: Everything working. Changed planner from 16 to 32. UART chanl2 poll 75 to 250. 
arc_tolerance_mm: 0.002
junction_deviation_mm: 0.01
verbose_errors: true
report_inches: false
enable_parking_override_control: false
use_line_numbers: false
planner_blocks: 32
stepping:
  engine: I2S_STREAM
  idle_ms: 0
  pulse_us: 4
  dir_delay_us: 1
  disable_delay_us: 0
i2so:
  bck_pin: gpio.22
  data_pin: gpio.21
  ws_pin: gpio.17
spi:
  miso_pin: gpio.19
  mosi_pin: gpio.23
  sck_pin: gpio.18
sdcard:
  card_detect_pin: NO_PIN
  cs_pin: gpio.5
start:
  must_home: false
  deactivate_parking: true
  check_limits: false
uart2:
  txd_pin: gpio.25
  rxd_pin: gpio.27
  rts_pin: NO_PIN
  cts_pin: NO_PIN
  baud: 1000000
  mode: 8N1
  passthrough_baud: 1000000
  passthrough_mode: 8N1
uart_channel2:
  report_interval_ms: 250
  uart_num: 2
user_outputs:
  digital0_pin: gpio.26:high
  digital1_pin: I2SO.23:high
coolant:
  mist_pin: gpio.4:high
  flood_pin: NO_PIN
  delay_ms: 0
probe:
  pin: gpio.2:low:pu
  toolsetter_pin: NO_PIN
  check_mode_start: true
  hard_stop: false
control:
  estop_pin: gpio.34
  safety_door_pin: NO_PIN
  reset_pin: NO_PIN
  feed_hold_pin: NO_PIN
  cycle_start_pin: NO_PIN
  macro0_pin: NO_PIN
  macro1_pin: NO_PIN
  macro2_pin: NO_PIN
  macro3_pin: NO_PIN
  fault_pin: NO_PIN
axes:
  homing_runs: 2
  x:
    steps_per_mm: 400
    max_rate_mm_per_min: 1800
    acceleration_mm_per_sec2: 50
    max_travel_mm: 407
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 220
      seek_mm_per_min: 900
      settle_ms: 400
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: gpio.32:pu:low
      limit_pos_pin: uart_channel2.0:low
      hard_limits: true
      pulloff_mm: 4
      standard_stepper:
        step_pin: i2so.2
        direction_pin: i2so.1
        disable_pin: i2so.0
  y:
    steps_per_mm: 400
    max_rate_mm_per_min: 1900
    acceleration_mm_per_sec2: 50
    max_travel_mm: 400
    soft_limits: true
    homing:
      cycle: 2
      positive_direction: false
      mpos_mm: 0
      feed_mm_per_min: 220
      seek_mm_per_min: 900
      settle_ms: 400
      seek_scaler: 1.1
      feed_scaler: 1.1
    motor0:
      limit_neg_pin: uart_channel2.1:low
      limit_pos_pin: gpio.33:pu:low
      hard_limits: true
      pulloff_mm: 4
      standard_stepper:
        step_pin: i2so.5
        direction_pin: i2so.4
        disable_pin: i2so.7
    motor1:
      limit_neg_pin: uart_channel2.2:low
      limit_pos_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 3.7
      standard_stepper:
        step_pin: i2so.10
        direction_pin: i2so.9
        disable_pin: i2so.8
  z:
    steps_per_mm: 400
    max_rate_mm_per_min: 400
    acceleration_mm_per_sec2: 30
    max_travel_mm: 57
    soft_limits: true
    homing:
      cycle: 1
      positive_direction: true
      mpos_mm: 0
      feed_mm_per_min: 150
      seek_mm_per_min: 450
      settle_ms: 600
    motor0:
      limit_all_pin: gpio.35:low
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: true
      pulloff_mm: 3
      standard_stepper:
        step_pin: i2so.13
        direction_pin: i2so.12
        disable_pin: i2so.15
  a:
    steps_per_mm: 177.8
    max_rate_mm_per_min: 24000
    acceleration_mm_per_sec2: 1800
    max_travel_mm: 36000
    soft_limits: false
    motor0:
      limit_all_pin: NO_PIN
      limit_neg_pin: NO_PIN
      limit_pos_pin: NO_PIN
      hard_limits: false
      pulloff_mm: 1
      standard_stepper:
        step_pin: i2so.18
        direction_pin: i2so.17
        disable_pin: i2so.16
uart1:
  txd_pin: gpio.15
  rxd_pin: gpio.16
  rts_pin: gpio.14
  baud: 9600
  mode: 8N1
ModbusVFD:
  uart_num: 1
  modbus_id: 1
  model: H100
  tool_num: 0
  spinup_ms: 10000
  spindown_ms: 10000
  cw_cmd: 05 00 49 ff 00 > 05 00 49 ff 00
  ccw_cmd: 05 00 4a ff 00 > 05 00 4a ff 00
  off_cmd: 05 00 4b ff 00 > 05 00 4b ff 00
  set_rpm_cmd: 06 02 01 rpm*10/60  > echo
  get_max_rpm_cmd: 03 00 05 00 01 > 03 02 maxrpm*60/10
  get_min_rpm_cmd: 03 00 0b 00 01 > 03 02 minrpm*60/10
  get_rpm_cmd: 03 02 20 00 01 > 03 02 rpm*60/10
  poll_ms: 250
  debug: 0
Laser:
  pwm_hz: 5000
  output_pin: gpio.12
  enable_pin: NO_PIN
  disable_with_s0: false
  s0_with_disable: true
  tool_num: 1
  speed_map: 0=0.000% 255=100.000%
  off_on_alarm: true
parking:
  enable: false
  axis: Z
  target_mpos_mm: -5
  rate_mm_per_min: 800
  pullout_distance_mm: 5
  pullout_rate_mm_per_min: 250
